REPO_COINES_PATH ?= ../../../submodules/coines

MAIN_FILE ?= low_threshold_interrupt.c

C_SRCS += \
../../../source/bmm150.c \
../common/common.c

INCLUDEPATHS += \
../../../source \
../common

include ../../../scripts/coines.mk